$engine: 3
$onesync: on
name: "Vila Amentista V1"
description: "Base de servidor FiveM - Vila Amentista V1"

tasks:
  # Baixar os resources do seu repositório
  - action: download_github
    src: https://github.com/claydevmoon/Vila_AmentistaV1
    ref: main
    subpath: resources
    dest: ./resources

  # Baixar server.cfg do seu repositório
  - action: download_file
    url: https://raw.githubusercontent.com/claydevmoon/Vila_AmentistaV1/main/server.cfg
    path: ./server.cfg

  # Baixar database.sql do seu repositório
  - action: download_file
    url: https://raw.githubusercontent.com/claydevmoon/Vila_AmentistaV1/main/database.sql
    path: ./database.sql
